# vim: ft=yaml
---
driver:
  name: docker
  image: debian:8

provisioner:
  name: salt_solo
  formula: crowd
  state_top:
    base:
      "*":
        - crowd
  pillars:
    top.sls:
      base:
        "*":
          - crowd

platforms:
  - name: debian

suites:
  - name: default
    provisioner:
      pillars:
        crowd.sls:
          crowd:
            enabled: true
            mockup: true

  - name: custom
    provisioner:
      pillars-from-files:
        crowd.sls: pillar-custom.sls
